// =====================================================================
// tb_core_instr.sv - RV32I core instruction test (self-checking)
//
// Runs instr_test.hex (all 37 RV32I instructions, generated by
// tools/gen_programs.py) on the real SoC and compares every result word
// stored in DMEM against instr_expected.hex, which comes from an
// independent instruction-set simulator (tools/rv32i_tools.py).
// =====================================================================
`timescale 1ns/1ps

module tb_core_instr;

    localparam real CLK_PERIOD_NS = 20.0;

    logic clk = 1'b0;
    logic rst_n;
    always #(CLK_PERIOD_NS/2.0) clk = ~clk;

    logic spi_sclk, spi_mosi, spi_cs_n, uart_tx_line, pwm_out, bus_error;

    soc_top #(
        .IMEM_INIT_FILE ("instr_test.hex"),
        .CFG_INIT_FILE  ("")
    ) u_dut (
        .clk(clk), .rst_n(rst_n),
        .spi_sclk(spi_sclk), .spi_mosi(spi_mosi), .spi_miso(1'b0), .spi_cs_n(spi_cs_n),
        .uart_tx_line(uart_tx_line), .uart_rx_line(1'b1),
        .pwm_out(pwm_out), .fan_rpm_in(16'd0),
        .bus_error(bus_error)
    );

    soc_assertions u_sva (
        .clk(clk), .rst_n(rst_n),
        .pc(u_dut.u_core.pc), .core_re(u_dut.core_dre), .core_we(u_dut.core_dwe),
        .core_rdata(u_dut.core_drdata), .bus_error(bus_error),
        .dmem_sel(u_dut.dmem_sel), .cfg_sel(u_dut.cfg_sel), .pwm_sel(u_dut.pwm_sel),
        .spi_sel(u_dut.spi_sel), .uart_sel(u_dut.uart_sel),
        .pwm_out(pwm_out), .pwm_en(u_dut.u_pwm_controller.en_reg),
        .pwm_duty(u_dut.u_pwm_controller.duty_reg), .pwm_fault(u_dut.u_pwm_controller.fault_reg),
        .pwm_failsafe(u_dut.u_pwm_controller.failsafe_active), .fan_rpm(16'd0),
        .spi_sclk(spi_sclk), .spi_mosi(spi_mosi), .spi_cs_n(spi_cs_n),
        .spi_busy(u_dut.u_spi_master.busy_reg), .spi_error(u_dut.u_spi_master.error_reg),
        .spi_start(u_dut.u_spi_master.start_pulse),
        .uart_tx_line(uart_tx_line), .uart_tx_en(u_dut.u_uart_top.tx_en),
        .uart_rx_valid(u_dut.u_uart_top.rx_valid_pulse),
        .uart_frame_err(u_dut.u_uart_top.frame_err_pulse)
    );

    logic [31:0] expected [0:255];
    int pass_count = 0, fail_count = 0;
    logic bus_error_seen = 1'b0;
    always @(posedge clk) if (bus_error === 1'b1) bus_error_seen <= 1'b1;

    initial begin
        int n;
        logic [31:0] pc_a, pc_b;

        $readmemh("instr_expected.hex", expected);
        n = expected[0];

        rst_n = 1'b0;
        repeat (5) @(posedge clk);
        if (u_dut.u_core.pc !== 32'h0) begin fail_count++; $display("[FAIL] PC != 0 in reset"); end
        else begin pass_count++; $display("[PASS] Reset: PC = 0"); end
        @(negedge clk); rst_n = 1'b1;

        repeat (2000) @(posedge clk);          // ~294 instructions, single cycle each

        $display("---- Comparing %0d result words against the ISS golden model ----", n);
        for (int i = 0; i < n; i++) begin
            if (u_dut.u_dmem.mem[i] === expected[i+1]) pass_count++;
            else begin
                fail_count++;
                $display("[FAIL] DMEM[%0d]: actual=0x%08h expected=0x%08h", i, u_dut.u_dmem.mem[i], expected[i+1]);
            end
        end
        if (fail_count == 0) $display("[PASS] all %0d instruction-test result words match the golden model", n);

        pc_a = u_dut.u_core.pc; repeat (4) @(posedge clk); pc_b = u_dut.u_core.pc;
        if (pc_a === pc_b) begin pass_count++; $display("[PASS] program reached its halt loop (PC=0x%03h)", pc_a); end
        else begin fail_count++; $display("[FAIL] program did not halt"); end

        if (!bus_error_seen) begin pass_count++; $display("[PASS] no bus_error during instruction test"); end
        else begin fail_count++; $display("[FAIL] unexpected bus_error"); end

        if (u_sva.fail_count == 0) begin pass_count++; $display("[PASS] zero SVA assertion failures"); end
        else begin fail_count++; $display("[FAIL] %0d SVA assertion failures", u_sva.fail_count); end

        $display("\n===================================================");
        $display(" CORE INSTRUCTION TEST: %0d PASSED, %0d FAILED", pass_count, fail_count);
        $display("===================================================");
        if (fail_count == 0) $display("RESULT: ALL TESTS PASSED");
        else                 $display("RESULT: %0d TEST(S) FAILED", fail_count);
        $finish;
    end
endmodule
